### ISSUE TITLE
Decorator dependency

### ISSUE THREAD

**Issue by create** [seamusabshere/py-upsert#1]
It appears that upsert depends on decorator, but doesn't declare this for installation via pip.

```
Collecting upsert==0.0.1 (from -r requirements_dev.txt (line 5))
  Downloading upsert-0.0.1.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/29/fz_jrcnx62z7h_m2k6dxv5j80000gn/T/pip-build-y0zkCy/upsert/setup.py", line 5, in <module>
        import upsert
      File "upsert/__init__.py", line 2, in <module>
        from decorator import decorator
    ImportError: No module named decorator
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/private/var/folders/29/fz_jrcnx62z7h_m2k6dxv5j80000gn/T/pip-build-y0zkCy/upsert/setup.py", line 5, in <module>

        import upsert

      File "upsert/__init__.py", line 2, in <module>

        from decorator import decorator

    ImportError: No module named decorator

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/29/fz_jrcnx62z7h_m2k6dxv5j80000gn/T/pip-build-y0zkCy/upsert
```

**Comment by create** [comment]
```
$ pip show upsert
---
Name: upsert
Version: 0.0.1
Location: /Users/jeffpyke/workspace/vamo/venv/lib/python2.7/site-packages
Requires: 
```

**Comment by ysoussov** [comment]
bump
